INSERT INTO public."Organisms" (
    cultivated, "hostPlantAnimal", "generalNotes", "museumNotes", "informationSource", 
    "speciesNameLevel1", "firstAuthor", "subspeciesLevel1", "speciesNameLevel2", "secondAuthor", 
    "subspeciesLevel2", "speciesNameLevel3", "thirdAuthor", "nomenclatureStatus", "nomenclatureLevel", 
    "scientificName", "authorName", "commonName", "publicationReference", "yearOfAuthorName", 
    "synonymName", "treeForm", "lifeForm", "ecologicalNiche", "speciesDescription", habitat, 
    "distributionArea", ethnobotany, "usageGroup", "endangeredRareSpecies", "createdAt", "updatedAt", 
    conservationstatus_id, groupoforganisms_id, kingdom_id, phylum_id, class_id, order_id, family_id, genus_id
)
VALUES 
    -- 1
    (false, 'Cây ăn quả', 'Thông tin chung về loài', 'Mẫu vật trong viện bảo tàng', 'Nguồn thông tin nghiên cứu', 
    'Mãng cầu', 'Nguyễn Văn A', 'Subspecies A1', 'Mãng cầu xanh', 'Lê Thị B', 
    'Subspecies B1', 'Mãng cầu đỏ', 'Trần Minh C', 'Được chấp nhận', 'Mức độ 2', 
    'Annona squamosa', 'Nguyễn Văn A', 'Mãng cầu', 'Tạp chí Sinh học, 2022', 2022, 
    'Mãng cầu giống', 'Cây thân gỗ', 'Cây ăn quả', 'Khí hậu nhiệt đới', 'Loài cây ăn quả phát triển nhanh.', 
    'Đồng bằng sông Cửu Long', 'Việt Nam', 'Được trồng phổ biến trong nông nghiệp', 'Nông sản', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 1, 1, 1, 2, 3, 4, 1),

    -- 2
    (true, 'Cây thuốc', 'Thực vật dùng trong y học', 'Mẫu vật trong phòng thí nghiệm', 'Tài liệu nghiên cứu y học', 
    'Nhân trần', 'Lê Thị D', 'Subspecies A2', 'Nhân trần tím', 'Phan Thiết E', 
    'Subspecies B2', 'Nhân trần trắng', 'Hoàng Minh F', 'Được chấp nhận', 'Mức độ 1', 
    'Andrographis paniculata', 'Lê Thị D', 'Nhân trần', 'Tạp chí Dược liệu, 2021', 2021, 
    'Nhân trần loại A', 'Cây bụi', 'Cây thuốc', 'Khu vực rừng nhiệt đới', 'Loài cây thuốc có tác dụng giảm viêm.', 
    'Các tỉnh miền Trung', 'Việt Nam', 'Sử dụng trong điều trị viêm nhiễm', 'Y học cổ truyền', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 2, 1, 1, 1, 3, 1, 2),

    -- 3
    (false, 'Cây trồng lương thực', 'Lúa gạo', 'Mẫu vật trong viện nghiên cứu', 'Nguồn tài liệu nông nghiệp', 
    'Lúa', 'Nguyễn Văn G', 'Subspecies A3', 'Lúa trắng', 'Phan Minh H', 
    'Subspecies B3', 'Lúa nếp', 'Trần Thị I', 'Được chấp nhận', 'Mức độ 3', 
    'Oryza sativa', 'Nguyễn Văn G', 'Lúa', 'Tạp chí Nông nghiệp, 2020', 2020, 
    'Lúa giống', 'Cây thân thảo', 'Cây lương thực', 'Môi trường đất ẩm', 'Loài cây trồng chính cho lương thực.', 
    'Đồng bằng sông Cửu Long', 'Việt Nam', 'Trồng phổ biến trong nông nghiệp', 'Lương thực', 
    false, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 3, 1, 1, 1, 1, 2, 1),

    -- 4
    (false, 'Thực vật cảnh', 'Cây cảnh trồng trong nhà', 'Mẫu vật trong triển lãm', 'Nguồn tài liệu sinh học', 
    'Cây đuôi công', 'Trương Minh K', 'Subspecies A4', 'Đuôi công đỏ', 'Lê Thị L', 
    'Subspecies B4', 'Đuôi công vàng', 'Nguyễn Văn M', 'Được chấp nhận', 'Mức độ 1', 
    'Codiaeum variegatum', 'Trương Minh K', 'Cây đuôi công', 'Tạp chí Sinh học cảnh quan, 2023', 2023, 
    'Cây trang trí', 'Cây bụi', 'Cây cảnh', 'Môi trường sống trong nhà', 'Cây cảnh trang trí nhà ở.', 
    'Các tỉnh miền Nam', 'Việt Nam', 'Được trồng phổ biến trong nội thất', 'Trang trí', 
    false, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 4, 1, 1, 3, 2, 1, 1),

    -- 5
    (true, 'Cây thực phẩm', 'Thực vật trồng để thu hoạch quả', 'Mẫu vật trong khu nghiên cứu nông nghiệp', 'Tài liệu thực phẩm', 
    'Đu đủ', 'Nguyễn Văn N', 'Subspecies A5', 'Đu đủ vàng', 'Trương Minh O', 
    'Subspecies B5', 'Đu đủ đỏ', 'Lê Minh P', 'Được chấp nhận', 'Mức độ 2', 
    'Carica papaya', 'Nguyễn Văn N', 'Đu đủ', 'Tạp chí Thực phẩm, 2022', 2022, 
    'Đu đủ giống', 'Cây thân gỗ', 'Cây thực phẩm', 'Môi trường đất cát', 'Loài cây thực phẩm dễ trồng và cho năng suất cao.', 
    'Miền Nam Việt Nam', 'Việt Nam', 'Sử dụng rộng rãi trong thực phẩm', 'Nông sản', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 5, 1, 2, 1, 1, 1, 2),

    -- 6
    (false, 'Động vật hoang dã', 'Động vật săn mồi', 'Mẫu vật trong bảo tàng động vật', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A6', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B6', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2022', 2022, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 6, 2, 1, 4, 1, 1, 1),

    -- 7
    (true, 'Cây thuốc quý', 'Cây có tác dụng chữa bệnh', 'Mẫu vật trong viện nghiên cứu', 'Thông tin y học', 
    'Sâm Ngọc Linh', 'Nguyễn Thị T', 'Subspecies A7', 'Sâm vàng', 'Trần Văn U', 
    'Subspecies B7', 'Sâm đỏ', 'Lê Minh V', 'Được chấp nhận', 'Mức độ 3', 
    'Panax vietnamensis', 'Nguyễn Thị T', 'Sâm Ngọc Linh', 'Tạp chí Y học, 2020', 2020, 
    'Sâm giống', 'Cây thân thảo', 'Cây thuốc', 'Khu vực rừng núi', 'Cây quý hiếm, có giá trị chữa bệnh.', 
    'Quảng Nam', 'Việt Nam', 'Sử dụng trong y học cổ truyền', 'Dược liệu', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 7, 1, 1, 1, 2, 1, 1),

    -- 8
    (false, 'Cây gỗ', 'Cây gỗ quý', 'Mẫu vật trong viện nghiên cứu', 'Tài liệu về gỗ', 
    'Cây gỗ Pơ Mu', 'Phan Thiết W', 'Subspecies A8', 'Pơ Mu đỏ', 'Lê Thiết X', 
    'Subspecies B8', 'Pơ Mu vàng', 'Trần Minh Y', 'Được chấp nhận', 'Mức độ 2', 
    'Fokienia hodginsii', 'Phan Thiết W', 'Pơ Mu', 'Tạp chí Sinh học Cây gỗ, 2023', 2023, 
    'Gỗ quý', 'Cây gỗ', 'Cây gỗ quý', 'Môi trường sống núi cao', 'Loài cây quý, gỗ dùng trong xây dựng.', 
    'Miền Trung', 'Việt Nam', 'Được trồng phổ biến trong lâm nghiệp', 'Lâm sản', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 8, 2, 1, 1, 1, 1, 1),

    -- 9
    (true, 'Cây ăn quả', 'Cây trồng trong vườn nhà', 'Mẫu vật trong khu trồng', 'Tài liệu về trái cây', 
    'Mận', 'Lê Quang Z', 'Subspecies A9', 'Mận đỏ', 'Nguyễn Phương A', 
    'Subspecies B9', 'Mận xanh', 'Phan Thiết B', 'Được chấp nhận', 'Mức độ 3', 
    'Prunus mume', 'Lê Quang Z', 'Mận', 'Tạp chí Trái cây, 2021', 2021, 
    'Mận giống', 'Cây thân gỗ', 'Cây ăn quả', 'Môi trường sống nhiệt đới', 'Cây ăn quả có quả nhỏ, vị ngọt.', 
    'Tây Bắc Việt Nam', 'Việt Nam', 'Sử dụng làm thực phẩm', 'Thực phẩm', 
    false, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 9, 1, 1, 1, 1, 1, 1),

    -- 10
    (false, 'Thực vật gia vị', 'Cây gia vị trong nông nghiệp', 'Mẫu vật trong viện nghiên cứu', 'Tài liệu gia vị', 
    'Gừng', 'Trần Thiết C', 'Subspecies A10', 'Gừng vàng', 'Lê Thiết D', 
    'Subspecies B10', 'Gừng trắng', 'Nguyễn Thi B', 'Được chấp nhận', 'Mức độ 2', 
    'Zingiber officinale', 'Trần Thiết C', 'Gừng', 'Tạp chí Gia vị, 2020', 2020, 
    'Gừng giống', 'Cây thân thảo', 'Cây gia vị', 'Môi trường đất ẩm', 'Loài cây gia vị phổ biến trong ẩm thực.', 
    'Miền Nam Việt Nam', 'Việt Nam', 'Được sử dụng rộng rãi trong nấu ăn', 'Gia vị', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 10, 2, 1, 1, 1, 1, 1),
    
    -- 11 đến 20 (Tiếp tục logic tương tự cho các bản ghi còn lại)
    (true, 'Cây thực phẩm', 'Cây trồng để thu hoạch quả', 'Mẫu vật trong khu nghiên cứu nông nghiệp', 'Tài liệu thực phẩm', 
    'Đu đủ', 'Nguyễn Văn N', 'Subspecies A5', 'Đu đủ vàng', 'Trương Minh O', 
    'Subspecies B5', 'Đu đủ đỏ', 'Lê Minh P', 'Được chấp nhận', 'Mức độ 2', 
    'Carica papaya', 'Nguyễn Văn N', 'Đu đủ', 'Tạp chí Thực phẩm, 2022', 2022, 
    'Đu đủ giống', 'Cây thân gỗ', 'Cây thực phẩm', 'Môi trường đất cát', 'Loài cây thực phẩm dễ trồng và cho năng suất cao.', 
    'Miền Nam Việt Nam', 'Việt Nam', 'Sử dụng rộng rãi trong thực phẩm', 'Nông sản', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    1, 1, 1, 2, 1, 1, 2, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 2, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 3, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 4, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 5, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 6, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 7, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 8, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 9, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 10, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 1, 2, 2, 6, 3, 3, 1),
	
	(false, 'Động vật hoang dã', 'Động vật ăn thịt', 'Mẫu vật trong viện bảo tàng', 'Nguồn nghiên cứu về động vật', 
    'Hổ Bengal', 'Lê Minh Q', 'Subspecies A1', 'Hổ trắng', 'Nguyễn Thị R', 
    'Subspecies B1', 'Hổ vàng', 'Trần Thiện S', 'Được chấp nhận', 'Mức độ 1', 
    'Panthera tigris', 'Lê Minh Q', 'Hổ Bengal', 'Tạp chí Động vật, 2021', 2021, 
    'Hổ giống', 'Động vật ăn thịt', 'Động vật hoang dã', 'Rừng nhiệt đới', 'Loài động vật ăn thịt, nguy cơ tuyệt chủng.', 
    'Rừng U Minh Thượng', 'Việt Nam', 'Bảo vệ động vật hoang dã', 'Động vật quý hiếm', 
    true, '2024-12-19 10:00:00+00', '2024-12-19 10:00:00+00', 
    2, 2, 2, 2, 6, 3, 3, 1);